### PR TITLE
make iptables Error judge with protocal to adapt both ipv4 and ipv6

### PR DESCRIPTION
**Pull request by mars1024**
When judging iptables Error,  some fixed strings are used, like "iptables: No chain/target/match by that name.\n", but when we use ip6tables in ipv6 protocal, the same return message is "ip6tables: No chain/target/match by that name.\n", these two strings mismatch. And this raises some troubles like [CI broken](https://travis-ci.org/containernetworking/plugins/jobs/524356979).

So I think we can add protocal to Error struct and make judgements with protocal together.

### CODE REVIEW

**Comment by mars1024** [comment]
@squeed  PTAL, thanks ~

**Comment by squeed** [comment]
That was quick :-)

**Comment by mars1024** [comment]
> That was quick :-)

Call me The Flash :)

**Comment by squeed** [comment]
LGTM.

**Pull request merged**
