### PR TITLE
*: refactor iptables invocation

### PR DESCRIPTION
**Pull request by jonboulle**
Centralise all invocations of iptables, so that the lock is used every
time it is called.

Follow up to https://github.com/coreos/go-iptables/pull/12#issuecomment-159138236 , /cc @vcaputo

### CODE REVIEW

**Comment by vcaputo** [comment]
lgtm

**Comment by jonboulle** [comment]
sure hope you're checking this stuff, hyuk hyuk

**Comment by vcaputo** [comment]
As closely as my stuff gets checked (https://github.com/coreos/coreos-overlay/pull/1639)

**Comment by jonboulle** [comment]
ouch

**Pull request merged**
